# db conf
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:io/github/tlh/jmb/mapper/xml/**.xml
  type-aliases-package: io.github.tlh.jmb.common.pojo
spring:
  datasource:
    url: jdbc:sqlite:sqlite/jmb.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: ALWAYS
      separator: ^; # 使用默认 ; 分隔符执行trigger报错，这里换成 ^;
      schema-locations:
        - classpath:dbs/sqlite/schema.sql
        - classpath:dbs/sqlite/trigger.sql

# website conf
comment:
  default:
    avatar: /default/images/avatar.png
github:
  callback: http://xiongsihao.com/github/callback  # 修改成自己应用回调地址
  client-id: Iv1.5f8c132f227f383c                 # 修改成自己github client-id
  client-secret: 755c85b587ee2734cf59572768bdd623da0b61ea     # 修改成自己github client-secret
image:
  upload:
    base-url: /website/upload/image
website:
  theme: "default"  # default,simple
  indexDir: /website/index
  markdownDir: /website/markdown-articles
  cookie:
    time: 864000
  webSiteTittle: "wuliling's 博客"
  webSiteDescription: "一个用Java写的Markdown博客"
  webSiteLogo: "https://i.328888.xyz/2023/02/05/NPLMJ.png"
  webSiteIcon:
  author: "wulilinghan"
  #authorAvatar: "https://cn.gravatar.com/userimage/176875695/30e6f4fb8ae8b9eef75989ac24806248.png"
  authorAvatar: "https://i.328888.xyz/2023/02/05/NPvYP.jpeg"
  footer:
    icp:            # 例如：粤公网安备 123456789号
    poweredBy: "java-markdown-blog"
    poweredByUrl: "https://github.com/wulilinghan/java-markdown-blog"
  gitTalk:
    enable:
    owner:
    admin:
    repo:
    clientId:
    secret:
  plugin-player: "false"  # 网易云播放器
  plugin-player-type: "neteasePlayer"   # 网易云播放器插件，有两种  netEasy-music ，neteasePlayer



