mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:com/github/wulilinghan/jmb/mapper/xml/**.xml
    type-aliases-package: com.github.wulilinghan.jmb.common.pojo
spring:
    datasource:
        url: jdbc:sqlite:dbs/sqlite/jmb.db
