# db conf
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:io/github/tlh/jmb/mapper/xml/**.xml
  type-aliases-package: io.github.tlh.jmb.common.pojo
spring:
  datasource:
    url: jdbc:sqlite:sqlite/jmb.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: ALWAYS
      separator: ^; # 使用默认 ; 分隔符执行trigger报错，这里换成 ^;
      schema-locations:
        - classpath:dbs/sqlite/schema.sql

# website conf
comment:
  default:
    avatar: /default/images/avatar.png
github:
  callback: http://xiongsihao.com/github/callback  # 修改成自己应用回调地址
  client-id: Iv1.5f8c132f227f383c                 # 修改成自己github client-id
  client-secret: 755c85b587ee2734cf59572768bdd623da0b61ea     # 修改成自己github client-secret
image:
  upload:
    base-url: d:/website/upload/image
website:
  theme:
    active: "default"  # 主题 default,simple
    default-theme:
      plugin-player: "true"  # 是否开启网易云播放器
      plugin-player-type: "netEasy-music"   # 网易云播放器插件，有两种  netEasy-music ，neteasePlayer
      netease-player-list-id: "2993302747"   # 网易云歌单id  例如此链接id=后面的数字 https://music.163.com/#/my/m/music/playlist?id=2993302747
      github: "https://github.com/wulilinghan"
      twitter: "isvling"
      qq: "1902325071"
    simple-theme:
      github: "https://github.com/wulilinghan"
      twitter: "https://twitter.com/isvling"
  index-dir: d:/website/index
  markdown-dir: D:\work-space\github\assets\markdown-articles
  cookie:
    time: 864000
  # 博主
  author: "wulilinghan"
  #authorAvatar: "https://cn.gravatar.com/userimage/176875695/30e6f4fb8ae8b9eef75989ac24806248.png"
  author-avatar: "https://i.328888.xyz/2023/02/05/NPvYP.jpeg"
  # 网站
  web-site-tittle: "wuliling's 博客"
  web-site-description: "一个用Java写的Markdown博客"
  web-site-logo: "https://i.328888.xyz/2023/02/05/NPLMJ.png"
  web-site-icon:
  footer:
    icp:                # 例如：粤公网安备 123456789号
    powered-by: "java-markdown-blog"
    powered-by-url: "https://github.com/wulilinghan/java-markdown-blog"
  # 评论 gitTalk未开发
  gitTalk:
    enable:
    owner:
    admin:
    repo:
    clientId:
    secret:




